# Generated by Django 3.2.9 on 2022-01-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_direct', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
